### ISSUE TITLE
Did you mean for-of?

### ISSUE THREAD

**Issue by yuchi** [chpmrc/zero-width-chrome-extension#1]
You use [`for in` here](https://github.com/chpmrc/zero-width-chrome-extension/blob/81dc6a0b7b89c234d1e86b9e035f25a87c903dc7/popup.js#L10) when probably you meant `for of`.

**Comment by chpmrc** [comment]
In this particular case the order doesn't matter but, yeah, `for of` would be better. Fixing it, thanks!
