### ISSUE TITLE
[Question] Do I still need this kind of protection in Chrome/Firefox/Tor Browser?!

### ISSUE THREAD

**Issue by CHEF-KOCH** [chpmrc/zero-width-chrome-extension#5]
Hello, first of all thanks for this interesting extension and the idea.

My main question is if I still have to install the extension in e.g. Chrome or if other Browsers protection mechanism protecting me against such kind of attacks with their integrated incognito/private browsing implementation?

I'm not entirely sure because Tor Browser seems to have several things integrated regarding this, same like Firefox but I'm not really involved into this entire topic so that's why I ask.

**Comment by chpmrc** [comment]
Uhh, I don't think revealing zero width characters is part of any browser's security roadmap so yes, if you're interested in this functionality you're going to have to use an extension.
